-- Databricks notebook source

optimize MailroomIncoming.iautoswitchoptoutrequested;
optimize MailroomIncoming.icancelledswitchresolutionfound;
optimize MailroomIncoming.icoolingoffperiodexpired;
optimize MailroomIncoming.ilikelysavingsopportunityfound;
optimize MailroomIncoming.imanualenergyswitchrequested;
optimize MailroomIncoming.isavingsopportunityrejected;
optimize MailroomIncoming.isupplierrequestedswitchcancelled;
optimize MailroomIncoming.iswitchcompleted;
optimize MailroomIncoming.iswitchcompletionunconfirmed;
optimize MailroomIncoming.iswitchdetailssenttosupplier;
optimize MailroomIncoming.iswitchexpired;
optimize MailroomIncoming.iswitchstarted;
optimize MailroomIncoming.iuserrequestedswitchcancelfailed;
optimize MailroomIncoming.iuserrequestedswitchcancellation;
optimize MailroomIncoming.iuserrequestedswitchcancelled;
optimize MailroomIncoming.preferences_iupdated;

-- COMMAND ----------


vacuum MailroomIncoming.iautoswitchoptoutrequested;
vacuum MailroomIncoming.icancelledswitchresolutionfound;
vacuum MailroomIncoming.icoolingoffperiodexpired;
vacuum MailroomIncoming.ilikelysavingsopportunityfound;
vacuum MailroomIncoming.imanualenergyswitchrequested;
vacuum MailroomIncoming.isavingsopportunityrejected;
vacuum MailroomIncoming.isupplierrequestedswitchcancelled;
vacuum MailroomIncoming.iswitchcompleted;
vacuum MailroomIncoming.iswitchcompletionunconfirmed;
vacuum MailroomIncoming.iswitchdetailssenttosupplier;
vacuum MailroomIncoming.iswitchexpired;
vacuum MailroomIncoming.iswitchstarted;
vacuum MailroomIncoming.iuserrequestedswitchcancelfailed;
vacuum MailroomIncoming.iuserrequestedswitchcancellation;
vacuum MailroomIncoming.iuserrequestedswitchcancelled;
vacuum MailroomIncoming.preferences_iupdated;
