-- Databricks notebook source

optimize MailroomIncoming.weflip_iautoswitchoptoutrequested;
optimize MailroomIncoming.weflip_icancelledswitchresolutionfound;
optimize MailroomIncoming.weflip_icoolingoffperiodexpired;
optimize MailroomIncoming.weflip_imanualenergyswitchrequested;
optimize MailroomIncoming.weflip_isavingsopportunityrejected;
optimize MailroomIncoming.weflip_isupplierrequestedswitchcancelled;
optimize MailroomIncoming.weflip_iswitchcompleted;
optimize MailroomIncoming.weflip_iswitchcompletionunconfirmed;
optimize MailroomIncoming.weflip_iswitchdetailssenttosupplier;
optimize MailroomIncoming.weflip_iswitchexpired;
optimize MailroomIncoming.weflip_iswitchstarted;
optimize MailroomIncoming.weflip_iuserrequestedswitchcancelfailed;
optimize MailroomIncoming.weflip_iuserrequestedswitchcancellation;
optimize MailroomIncoming.weflip_iuserrequestedswitchcancelled;
optimize MailroomIncoming.weflip_preferences_iupdated;

-- COMMAND ----------


vacuum MailroomIncoming.weflip_iautoswitchoptoutrequested;
vacuum MailroomIncoming.weflip_icancelledswitchresolutionfound;
vacuum MailroomIncoming.weflip_icoolingoffperiodexpired;
vacuum MailroomIncoming.weflip_imanualenergyswitchrequested;
vacuum MailroomIncoming.weflip_isavingsopportunityrejected;
vacuum MailroomIncoming.weflip_isupplierrequestedswitchcancelled;
vacuum MailroomIncoming.weflip_iswitchcompleted;
vacuum MailroomIncoming.weflip_iswitchcompletionunconfirmed;
vacuum MailroomIncoming.weflip_iswitchdetailssenttosupplier;
vacuum MailroomIncoming.weflip_iswitchexpired;
vacuum MailroomIncoming.weflip_iswitchstarted;
vacuum MailroomIncoming.weflip_iuserrequestedswitchcancelfailed;
vacuum MailroomIncoming.weflip_iuserrequestedswitchcancellation;
vacuum MailroomIncoming.weflip_iuserrequestedswitchcancelled;
vacuum MailroomIncoming.weflip_preferences_iupdated;
